import "./globals.css";
import { montserrat } from "./ui/fonts";
import NavBar from "./components/NavBar";
import { ThemeProvider } from "./ThemeContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider>
        <body className={`${montserrat.className} antialiased`}>
          <NavBar />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
